### PR TITLE
Contributing basic portrairts (static) for Avali

### PR DESCRIPTION
**Pull request by Blackhole32**
I've finished the first batch of Avali portraits with basic colors and one type of cloth. Currently, there are 276 images. An example in the game can be seen [here](https://cdn.discordapp.com/attachments/303942362865074179/561266423457120256/unknown.png)

### CODE REVIEW

**Comment by atakiya** [comment]
There's some oddities about the clothes/hairstyles and such, but I will look upon it and fix it if possible.
(nothing graphical, just the `.txt` configurations might be a little off)

Despite that I'm gonna go ahead and merge this into the dev branch already to phase out the old portraits and prepare everything for an update.

On another note, if you wanna be added as a contributor on the Steam page (on the sidebar), feel free to send me a friendrequest and I will add you there.
Else I will of course link you on the credits as well. If you have a certain URL/webpage you want me to put there, tell me.

**Comment by Blackhole32** [comment]
The clothes/hairstyles are currently a failure as it required a .mesh, which is impossible at the moment. However, I left the config there just in case I've managed to pull it off.

Anyway, I'm off to work, good luck ' v ' /

**Comment by atakiya** [comment]
Ah, that explains that then. No worries in that case.

And thanks, you have a good day at work \\^^

**Comment by Blackhole32** [comment]
Anyway Avunia, if I upload the portraits on separate mod first, is it OK? It'd only be the portraits I made and for the contribution part, you can link to my mod?

**Comment by Blackhole32** [comment]
I plan to upload the portraits-only first on a separate mod. For contribution link, you can link to that when you update '  ' /

**Comment by atakiya** [comment]
Sure thing!

**Pull request merged**
